import { Listing, Broker } from './supabase'

export const mockListings: Listing[] = [
  {
    id: '1', slug: 'abc-plumbing-services-denver-co',
    listingTitle: 'ABC Plumbing Services — Denver, CO',
    askingPrice: 850000, cashFlow: 220000, grossRevenue: 1200000, ebitda: 185000,
    location: 'Denver, Colorado', state: 'Colorado',
    category: 'Construction & Engineering > Plumbing',
    description: 'Established plumbing company with 22 years of operation serving residential and commercial clients throughout the Denver metro area. Loyal customer base of 800+ recurring clients. Owner retiring after building this business from the ground up.',
    yearEstablished: 2002, numberOfEmployees: '8 (6 Full-time, 2 Part-time)',
    brokerName: 'Michael Torres', brokerPhone: '303-555-0182', brokerFirm: 'Rocky Mountain Business Brokers',
    agentUrl: '#', realEstate: 'Leased', facilities: '$125,000 in equipment and vehicles',
    growthOpportunity: 'Expand into HVAC services, hire additional technicians',
    financing: 'Seller financing available up to 20%',
    supportAndTraining: '6 months full training and transition support',
    competition: '3 main competitors in the metro area',
    franchise: 'Independent', ffe: '$125,000 included', inventory: '$18,000 included',
    reasonForSelling: 'Retirement', homeBased: 'No', buildingSf: 3200,
    sellerType: 'agent', url: 'https://bizbuysell.com', scrapedAt: '2026-04-03T00:45:13Z',
    featured: true
  },
  {
    id: '2', slug: 'sunbelt-landscaping-phoenix-az',
    listingTitle: 'Sunbelt Landscaping & Maintenance — Phoenix, AZ',
    askingPrice: 425000, cashFlow: 130000, grossRevenue: 680000, ebitda: 110000,
    location: 'Phoenix, Arizona', state: 'Arizona',
    category: 'Home & Garden > Landscaping',
    description: 'Owner-operated landscaping business with 15 years serving high-end residential communities in North Scottsdale and Paradise Valley. 95 recurring maintenance contracts. Owner is 64 and ready to retire.',
    yearEstablished: 2009, numberOfEmployees: '6 (4 Full-time, 2 Seasonal)',
    brokerName: 'Sandra Reyes', brokerPhone: '602-555-0134', brokerFirm: 'Desert Southwest Business Sales',
    agentUrl: '#', realEstate: 'Home-Based', facilities: '$85,000 in equipment',
    growthOpportunity: 'Add hardscaping and pool services',
    financing: 'SBA pre-qualified',
    supportAndTraining: '90 days transition support',
    competition: 'Fragmented local market',
    franchise: 'Independent', ffe: '$85,000 included', inventory: '$8,000 included',
    reasonForSelling: 'Owner retiring', homeBased: 'Home-Based', buildingSf: 0,
    sellerType: 'agent', url: 'https://bizbuysell.com', scrapedAt: '2026-04-03T00:45:13Z',
    featured: false
  },
  {
    id: '3', slug: 'premier-hvac-solutions-charlotte-nc',
    listingTitle: 'Premier HVAC Solutions — Charlotte, NC',
    askingPrice: 1200000, cashFlow: 310000, grossRevenue: 2100000, ebitda: 275000,
    location: 'Charlotte, North Carolina', state: 'North Carolina',
    category: 'Construction & Engineering > HVAC',
    description: 'Full-service HVAC installation and maintenance company serving residential and light commercial clients. 18 years of operation, stellar reputation with 4.9 Google rating from 340+ reviews. Founder turning 67 and transitioning to retirement.',
    yearEstablished: 2006, numberOfEmployees: '14 (12 Full-time, 2 Part-time)',
    brokerName: 'Robert Kincaid', brokerPhone: '704-555-0291', brokerFirm: 'Carolinas Business Group',
    agentUrl: '#', realEstate: 'Leased', facilities: '$320,000 in vehicles and equipment',
    growthOpportunity: 'Add commercial HVAC and service agreements',
    financing: 'SBA 7(a) eligible, seller will carry 10%',
    supportAndTraining: '12 months training, will introduce all key accounts',
    competition: '2 major franchise competitors',
    franchise: 'Independent', ffe: '$320,000 included', inventory: '$42,000 included',
    reasonForSelling: 'Retirement — owner turning 67',
    homeBased: 'No', buildingSf: 5500,
    sellerType: 'agent', url: 'https://bizbuysell.com', scrapedAt: '2026-04-03T00:45:13Z',
    featured: true
  },
  {
    id: '4', slug: 'main-street-bakery-cafe-portland-or',
    listingTitle: 'Main Street Bakery & Café — Portland, OR',
    askingPrice: 285000, cashFlow: 78000, grossRevenue: 520000, ebitda: 65000,
    location: 'Portland, Oregon', state: 'Oregon',
    category: 'Restaurants & Food > Bakery',
    description: 'Beloved neighborhood bakery and café with 12 years at the same location. Known for artisan breads, pastries, and local coffee. Loyal neighborhood following. Owners are a husband-wife team retiring together.',
    yearEstablished: 2012, numberOfEmployees: '7 (3 Full-time, 4 Part-time)',
    brokerName: 'Lisa Park', brokerPhone: '503-555-0178', brokerFirm: 'Pacific Northwest Business Advisors',
    agentUrl: '#', realEstate: 'Leased', facilities: '$95,000 commercial kitchen equipment',
    growthOpportunity: 'Expand catering, add online ordering',
    financing: 'Seller financing available',
    supportAndTraining: '60 days full training including recipes',
    competition: '2 coffee chains nearby, no direct bakery competitor',
    franchise: 'Independent', ffe: '$95,000 included', inventory: '$12,000 included',
    reasonForSelling: 'Owners retiring together',
    homeBased: 'No', buildingSf: 1800,
    sellerType: 'agent', url: 'https://bizbuysell.com', scrapedAt: '2026-04-03T00:45:13Z',
    featured: false
  },
  {
    id: '5', slug: 'lakeside-auto-repair-minneapolis-mn',
    listingTitle: 'Lakeside Auto Repair — Minneapolis, MN',
    askingPrice: 595000, cashFlow: 165000, grossRevenue: 890000, ebitda: 142000,
    location: 'Minneapolis, Minnesota', state: 'Minnesota',
    category: 'Automotive > Auto Repair',
    description: 'Full-service auto repair shop with 25 years at the same location. Trusted AAA-approved facility with loyal customer base of 1,200+ active clients. Technician certifications transfer. Owner retiring after 25 years.',
    yearEstablished: 1999, numberOfEmployees: '9 (7 Full-time, 2 Part-time)',
    brokerName: 'Thomas Berg', brokerPhone: '612-555-0345', brokerFirm: 'Midwest Business Exchange',
    agentUrl: '#', realEstate: 'Owner will lease to buyer', facilities: '$185,000 in lifts and diagnostic equipment',
    growthOpportunity: 'Add EV servicing, fleet contracts',
    financing: 'SBA pre-qualified, real estate available separately',
    supportAndTraining: '6 months full training',
    competition: 'Dealer service centers and 1 national chain nearby',
    franchise: 'Independent', ffe: '$185,000 included', inventory: '$28,000 included',
    reasonForSelling: 'Retirement after 25 years',
    homeBased: 'No', buildingSf: 6200,
    sellerType: 'agent', url: 'https://bizbuysell.com', scrapedAt: '2026-04-03T00:45:13Z',
    featured: false
  },
  {
    id: '6', slug: 'bright-futures-cleaning-austin-tx',
    listingTitle: 'Bright Futures Cleaning Services — Austin, TX',
    askingPrice: 195000, cashFlow: 68000, grossRevenue: 340000, ebitda: 58000,
    location: 'Austin, Texas', state: 'Texas',
    category: 'Services > Cleaning',
    description: 'Residential and commercial cleaning company serving 85 recurring clients in the Austin metro area. 10 trained cleaning staff. Systems and processes fully documented. Owner built this from scratch 11 years ago and is now retiring.',
    yearEstablished: 2013, numberOfEmployees: '10 (4 Full-time, 6 Part-time)',
    brokerName: 'Jennifer Walsh', brokerPhone: '512-555-0267', brokerFirm: 'Lone Star Business Brokers',
    agentUrl: '#', realEstate: 'Home-Based', facilities: '$22,000 in equipment',
    growthOpportunity: 'Commercial contracts, post-construction cleaning',
    financing: 'Seller financing available',
    supportAndTraining: '90 days full transition',
    competition: '2 franchise competitors in market',
    franchise: 'Independent', ffe: '$22,000 included', inventory: '$5,000 included',
    reasonForSelling: 'Retiring',
    homeBased: 'Home-Based', buildingSf: 0,
    sellerType: 'agent', url: 'https://bizbuysell.com', scrapedAt: '2026-04-03T00:45:13Z',
    featured: false
  }
]

export const mockBrokers: Broker[] = [
  {
    id: '1', name: 'Michael Torres', firm: 'Rocky Mountain Business Brokers',
    phone: '303-555-0182', email: 'michael@rmbbrokers.com',
    website: 'https://rmbbrokers.com',
    states: ['Colorado', 'Wyoming', 'Utah'],
    specialties: ['Plumbing', 'HVAC', 'Construction'],
    bio: 'Specializing in retirement-driven business sales for 18 years. Closed 200+ transactions. SBA lending expert.',
    photo_url: '', featured: true,
    stripe_customer_id: '', subscription_status: 'active',
    created_at: '2026-01-01T00:00:00Z'
  },
  {
    id: '2', name: 'Sandra Reyes', firm: 'Desert Southwest Business Sales',
    phone: '602-555-0134', email: 'sandra@desertsw.com',
    website: 'https://desertsw.com',
    states: ['Arizona', 'Nevada', 'New Mexico'],
    specialties: ['Landscaping', 'Home Services', 'Retail'],
    bio: 'Former small business owner who now helps founders exit on their own terms. 12 years brokering retirement sales.',
    photo_url: '', featured: true,
    stripe_customer_id: '', subscription_status: 'active',
    created_at: '2026-01-15T00:00:00Z'
  },
  {
    id: '3', name: 'Robert Kincaid', firm: 'Carolinas Business Group',
    phone: '704-555-0291', email: 'robert@carolinasbiz.com',
    website: 'https://carolinasbiz.com',
    states: ['North Carolina', 'South Carolina', 'Virginia'],
    specialties: ['HVAC', 'Manufacturing', 'Distribution'],
    bio: 'M&A advisor with a focus on established businesses in the $500K–$5M range. Expert in SBA financing structures.',
    photo_url: '', featured: false,
    stripe_customer_id: '', subscription_status: 'active',
    created_at: '2026-02-01T00:00:00Z'
  }
]
